public_addr = "${SERVER_ADDR}:10501"
#bind_address = "0.0.0.0:10501"
scheduler_url = "${SCHEDULER_ADDR}"
cache_dir = "/tmp/toolchains"

[scheduler_auth]
type = "token"
token = "${AUTH_TOKEN}"

[builder]
type = "overlay"
build_dir = "/tmp/sccache-build"
bwrap_path = "/usr/bin/bwrap"
